name: Remote execution Cypress

on:
  schedule:
    - cron: '0 2 * * 5,6'
# * minute (0 - 59) # * hour (0 - 23) # * day of the month (1 - 31) # * month (1 - 12 or JAN-DEC) # * day of the week (0 - 6 or SUN-SAT)
  push: 
    branches:
    - main   

jobs:
 cypress-run:
    name: Test Scenarios execution
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout del código
      uses: actions/checkout@v4

    - name: Cypress run
      uses: cypress-io/github-action@v6
      with: 
        browser: chrome
        headed: true
    # after the test run completes store videos and any screenshots
    - uses: actions/upload-artifact@v4
       # add the line below to store screenshots only on failures
      if: failure()
      with:
         name: Fail screenShots
         path: cypress/screenshots
  
    - uses: actions/upload-artifact@v4
      if: always()
      with:
         name: Video of execution
         path: cypress/videos
    - uses: actions/upload-artifact@v4
      with:
         name: Report html
         path: cypress/reports/html/index.html

    