name: Remote execution Cypress

on: push

jobs:
 cypress-run:
    name: Cypress run
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout del código
      uses: actions/checkout@v4

    - name: Cypress run
      uses: cypress-io/github-action@v6
      with: 
        browser: chrome
        headed: true

    